### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by biuboomc** [SocialSisterYi/xuexiaoyi-to-xuexitong-tampermonkey-proxy#12]
192.168.1.100 - - [24/Oct/2022 17:37:51] "POST //v1/cx HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\new\xuexiaoyi-to-xuexitong-tampermonkey-proxy\app.py", line 104, in searchView
    answer = searchXuexiaoyi(question)  # 进行搜题
  File "C:\Users\lenovo\Desktop\new\xuexiaoyi-to-xuexitong-tampermonkey-proxy\app.py", line 45, in searchXuexiaoyi
    xxy.search(question)
  File "C:\Users\lenovo\Desktop\new\xuexiaoyi-to-xuexitong-tampermonkey-proxy\xuexiaoyi_API.py", line 69, in search
    raise APIError(code, resp_json['err_tips'])
xuexiaoyi_API.APIError: 10024:很抱歉，您请求的次数已超限

**Comment by biuboomc** [comment]
字体的解密是成功的，但是搜题时报错；
以及如何抓取学小易的openid呢，还是说并不一定要修改openid

**Comment by SocialSisterYi** [comment]
> 字体的解密是成功的，但是搜题时报错；
> 以及如何抓取学小易的openid呢，还是说并不一定要修改openid

安卓端使用canary进行抓包，如安卓7以上需要root并添加系统证书，进入微信小程序和通过微信小程序搜题时，了req header中就会存在这个字段
